version: '2'

networks:
  int-net:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - int-net
  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
      - '29092:29092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    depends_on:
      - zookeeper
    networks:
      - int-net
  mongodb:
    image: mongo:latest 
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - int-net

  mocked_subscribed:
    image: 'mockedsubscriber'
    ports:
      - '1666:5000'
    networks:
      - int-net 

  handler:
    image: 'handler'
    depends_on:
      - kafka
    links:
      - kafka:kafka
    ports:
      - '8088:8088'
    networks:
      - int-net
  sender:
    image: 'sender'
    depends_on:
      - mongodb
      - kafka
    links:
      - kafka:kafka
      - mongodb:mongodb
    environment:
     - MONGODB_URI=mongodb://mongodb/unreaded
    ports:
      - '8089:8089'
    networks:
      - int-net
  reader:
    image: 'reader'
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
    environment:
     - MONGODB_URI=mongodb://mongodb/unreaded
    ports:
      - '8090'
    networks:
      - int-net

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongodb_data:
    driver: local
